1.20.3 and 1.20.4 support.
SkytAsul/GlowingEntities pull request #12
Opened 2024-01-18 14:19 UTC by aematsubara

Tested in my Roulette plugin, working correctly.

2024-01-18 17:33 UTC, SkytAsul requested changes

2024-01-18 17:33 UTC, SkytAsul commented on src/main/java/fr/skytasul/glowingentities/GlowingEntities.java
> +				mappings = version == 20 && versionMinor == 1 ? ProtocolMappings.V1_20 : ProtocolMappings.getMappings(version, versionMinor);
Why that? The #getMappings function is made to handle those cases.

2024-01-18 17:33 UTC, SkytAsul commented on src/main/java/fr/skytasul/glowingentities/GlowingEntities.java
> +					"am",
You should not change the mapping of an existing version. "ab" is the field for 1.20, why change it?

2024-01-18 17:55 UTC, aematsubara commented on src/main/java/fr/skytasul/glowingentities/GlowingEntities.java
> +				mappings = version == 20 && versionMinor == 1 ? ProtocolMappings.V1_20 : ProtocolMappings.getMappings(version, versionMinor);
Using your current GlowingEntities class on a 1.20.1 server will give you the mappings V1_20_2 instead of V1_20 (the correct one), causing issues.

```
[14:52:05 INFO]: [GlowingEntities] [GlowingEntities] Found server version 1.20.1
[14:52:05 WARN]: [GlowingEntities] [GlowingEntities] Loaded not matching version of the mappings for your server version (1.20.1)
[14:52:05 INFO]: [GlowingEntities] [GlowingEntities] Loaded mappings V1_20_2
```

2024-01-18 17:59 UTC, aematsubara commented on src/main/java/fr/skytasul/glowingentities/GlowingEntities.java
> +					"am",
Because that's not the correct EntityType.MARKER field; in 1.20 is "am" not "ab" https://mappings.cephx.dev/1.20/net/minecraft/world/entity/EntityType.html

From mappings V1_17 to V1_19 marker type ids are correct, but from V1_19_3 (it uses "ab" from the previous mapping instead of using "ac" https://mappings.cephx.dev/1.19.3/net/minecraft/world/entity/EntityType.html) it's wrong

2024-01-18 19:16 UTC, SkytAsul commented on src/main/java/fr/skytasul/glowingentities/GlowingEntities.java
> +				mappings = version == 20 && versionMinor == 1 ? ProtocolMappings.V1_20 : ProtocolMappings.getMappings(version, versionMinor);
Then it's an issue with the algorithm, you should not put a case here. I'll see how to change that.

2024-01-18 19:22 UTC, SkytAsul commented on src/main/java/fr/skytasul/glowingentities/GlowingEntities.java
> +					"am",
Oh yeah you're right! It's actually not impactful on the util but yeah it's better to have the right field.

2024-01-18 19:25 UTC, SkytAsul commented on src/main/java/fr/skytasul/glowingentities/GlowingEntities.java
> +				mappings = version == 20 && versionMinor == 1 ? ProtocolMappings.V1_20 : ProtocolMappings.getMappings(version, versionMinor);
Please remove this change, after I merge your PR I'll commit a fix to the version choice algorithm.

2024-01-18 19:25 UTC, SkytAsul commented on src/main/java/fr/skytasul/glowingentities/GlowingEntities.java
> +				return lastGoodMajor;
Please remove this change, after I merge your PR I'll commit a fix to the version choice algorithm.

2024-01-18 20:01 UTC, aematsubara commented on src/main/java/fr/skytasul/glowingentities/GlowingEntities.java
> +				mappings = version == 20 && versionMinor == 1 ? ProtocolMappings.V1_20 : ProtocolMappings.getMappings(version, versionMinor);
> Then it's an issue with the algorithm, you should not put a case here. I'll see how to change that.

Yes, it was a quick fix since I was in a hurry to udpate my plugin and my brain wasn't thinking at that moment

> Please remove this change, after I merge your PR I'll commit a fix to the version choice algorithm.

I think I did, I'm new to this git stuff so I'm not sure

2024-01-18 20:04 UTC, SkytAsul commented
Thanks! I'll merge tomorrow!

2024-01-19 09:28 UTC, SkytAsul approved these changes

2024-01-19 09:29 UTC, merged

2024-01-19 09:30 UTC, SkytAsul commented
Thank you for your contribution! You did well even if you're new to git :)